/* JS */ gapi.loaded_0(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var na,pa,ya,Aa,Ba,Ca,Ha;_.ka=function(a){return function(){return _.ha[a].apply(this,arguments)}};_.ha=[];na=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};pa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ya=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};Aa=ya(this);Ba=function(a,b){if(b)a:{var c=Aa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&pa(c,a,{configurable:!0,writable:!0,value:b})}};
Ba("Symbol",function(a){if(a)return a;var b=function(e,f){this.JM=e;pa(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.JM};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
Ba("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=Aa[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&pa(d.prototype,a,{configurable:!0,writable:!0,value:function(){return Ca(na(this))}})}return a});Ca=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.Da=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:na(a)}};_.Fa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)Ha=Object.setPrototypeOf;else{var Ia;a:{var Ja={a:!0},Ma={};try{Ma.__proto__=Ja;Ia=Ma.a;break a}catch(a){}Ia=!1}Ha=Ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
_.Na=Ha;Ba("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});var Qa=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
Ba("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Qa(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});var Ra=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
Ba("Array.prototype.keys",function(a){return a?a:function(){return Ra(this,function(b){return b})}});Ba("Array.prototype.values",function(a){return a?a:function(){return Ra(this,function(b,c){return c})}});var Sa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};Ba("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Sa(b,d)&&c.push(b[d]);return c}});
Ba("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});Ba("Array.prototype.entries",function(a){return a?a:function(){return Ra(this,function(b,c){return[b,c]})}});
Ba("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});Ba("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});Ba("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Qa(this,b,"includes").indexOf(b,c||0)}});
Ba("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Sa(b,d)&&c.push([d,b[d]]);return c}});var Ta="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Sa(d,e)&&(a[e]=d[e])}return a};Ba("Object.assign",function(a){return a||Ta});
Ba("Array.prototype.flat",function(a){return a?a:function(b){b=void 0===b?1:b;for(var c=[],d=0;d<this.length;d++){var e=this[d];Array.isArray(e)&&0<b?(e=Array.prototype.flat.call(e,b-1),c.push.apply(c,e)):c.push(e)}return c}});
Ba("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!Sa(l,f)){var m=new b;pa(l,f,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(r){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,k=function(l){this.Ca=(g+=Math.random()+1).toString();if(l){l=_.Da(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("b");d(l);if(!Sa(l,f))throw Error("c`"+l);l[f][this.Ca]=m;return this};k.prototype.get=function(l){return c(l)&&Sa(l,f)?l[f][this.Ca]:void 0};k.prototype.has=function(l){return c(l)&&Sa(l,f)&&Sa(l[f],this.Ca)};k.prototype.delete=
function(l){return c(l)&&Sa(l,f)&&Sa(l[f],this.Ca)?delete l[f][this.Ca]:!1};return k});
Ba("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.Da([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!m.next().done?!1:!0}catch(r){return!1}}())return a;var b=new WeakMap,c=function(k){this.mf={};this.Oe=
f();this.size=0;if(k){k=_.Da(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.mf[m.id]=[]);m.le?m.le.value=l:(m.le={next:this.Oe,Oi:this.Oe.Oi,head:this.Oe,key:k,value:l},m.list.push(m.le),this.Oe.Oi.next=m.le,this.Oe.Oi=m.le,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.le&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.mf[k.id],k.le.Oi.next=k.le.next,k.le.next.Oi=
k.le.Oi,k.le.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.mf={};this.Oe=this.Oe.Oi=f();this.size=0};c.prototype.has=function(k){return!!d(this,k).le};c.prototype.get=function(k){return(k=d(this,k).le)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),
n;!(n=m.next()).done;)n=n.value,k.call(l,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++g,b.set(l,m)):m="p_"+l;var n=k.mf[m];if(n&&Sa(k.mf,m))for(k=0;k<n.length;k++){var r=n[k];if(l!==l&&r.key!==r.key||l===r.key)return{id:m,list:n,index:k,le:r}}return{id:m,list:n,index:-1,le:void 0}},e=function(k,l){var m=k.Oe;return Ca(function(){if(m){for(;m.head!=k.Oe;)m=m.Oi;for(;m.next!=m.head;)return m=
m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},f=function(){var k={};return k.Oi=k.next=k.head=k},g=0;return c});
Ba("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.Da([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=function(c){this.Ha=new Map;if(c){c=
_.Da(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.Ha.size};b.prototype.add=function(c){c=0===c?0:c;this.Ha.set(c,c);this.size=this.Ha.size;return this};b.prototype.delete=function(c){c=this.Ha.delete(c);this.size=this.Ha.size;return c};b.prototype.clear=function(){this.Ha.clear();this.size=0};b.prototype.has=function(c){return this.Ha.has(c)};b.prototype.entries=function(){return this.Ha.entries()};b.prototype.values=function(){return this.Ha.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.Ha.forEach(function(f){return c.call(d,f,f,e)})};return b});_.p={};_.Ua=_.Ua||{};_.C=this||self;_.Va="closure_uid_"+(1E9*Math.random()>>>0);_.K=function(a,b){a=a.split(".");var c=_.C;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};
_.O=function(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Lo=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};
gadgets=window.gadgets||{};osapi=window.osapi=window.osapi||{};

window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
blogger:{url:":socialhost:/:session_prefix:_/widget/render/blogger?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},appfinder:{url:"https://workspace.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{rpc:"/rpc",root:"https://content.googleapis.com",
"root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var fb,gb,ib;_.Xa=function(a,b){return 0<=(0,_.Wa)(a,b)};_.Ya=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Za=function(){};_.$a=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};_.eb=function(a){var b=_.$a(a);return"array"==b||"object"==b&&"number"==typeof a.length};fb=function(a,b,c){return a.call.apply(a.bind,arguments)};
gb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.P=function(a,b,c){_.P=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fb:gb;return _.P.apply(null,arguments)};_.hb=function(){return Date.now()};ib=function(a){return a};
_.Wa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.kb=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.lb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.mb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d};_.nb=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.ob=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.pb=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};
var rb;_.qb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.sb=function(a,b){var c=0;a=(0,_.qb)(String(a)).split(".");b=(0,_.qb)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=rb(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||rb(0==f[2].length,0==g[2].length)||rb(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c};
rb=function(a,b){return a<b?-1:a>b?1:0};
a:{var vb=_.C.navigator;if(vb){var wb=vb.userAgent;if(wb){_.ub=wb;break a}}_.ub=""}_.yb=function(a){return-1!=_.ub.indexOf(a)};
var Ab;_.zb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ab="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Bb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ab.length;f++)c=Ab[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Cb=function(){return _.yb("Opera")};_.Db=function(){return _.yb("Trident")||_.yb("MSIE")};_.Eb=function(){return _.yb("Firefox")||_.yb("FxiOS")};_.Fb=function(){return(_.yb("Chrome")||_.yb("CriOS"))&&!_.yb("Edge")};
_.Gb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
var Jb;_.Kb=function(){if(void 0===Jb){var a=null,b=_.C.trustedTypes;if(b&&b.createPolicy)try{a=b.createPolicy("goog#html",{createHTML:ib,createScript:ib,createScriptURL:ib})}catch(c){_.C.console&&_.C.console.error(c.message)}Jb=a}return Jb};
var Mb,Lb;_.Nb=function(a,b){this.YL=a===Lb&&b||"";this.bP=Mb};_.Nb.prototype.Ch=!0;_.Nb.prototype.nd=_.ka(4);_.Ob=function(a){return a instanceof _.Nb&&a.constructor===_.Nb&&a.bP===Mb?a.YL:"type_error:Const"};_.Pb=function(a){return new _.Nb(Lb,a)};Mb={};Lb={};
_.Sb=function(a,b){this.fK=b===_.Qb?a:""};_.Sb.prototype.Ch=!0;_.Sb.prototype.nd=_.ka(3);_.Sb.prototype.fA=!0;_.Sb.prototype.uh=_.ka(6);_.Qb={};_.Tb=new _.Sb("about:invalid#zClosurez",_.Qb);
_.Vb=function(a,b){this.eK=b===_.Ub?a:""};_.Vb.prototype.Ch=!0;_.Vb.prototype.nd=_.ka(2);_.Ub={};_.Wb=new _.Vb("",_.Ub);
_.Yb={};_.Zb=function(a,b){this.dK=b===_.Yb?a:"";this.Ch=!0};_.ac=function(a){a=_.Ob(a);return 0===a.length?$b:new _.Zb(a,_.Yb)};_.Zb.prototype.nd=_.ka(1);var $b=new _.Zb("",_.Yb);
var bc;_.cc=function(a,b,c){this.cK=c===bc?a:"";this.yQ=b};_.cc.prototype.fA=!0;_.cc.prototype.uh=_.ka(5);_.cc.prototype.Ch=!0;_.cc.prototype.nd=_.ka(0);_.dc=function(a){if(a instanceof _.cc&&a.constructor===_.cc)return a.cK;_.$a(a);return"type_error:SafeHtml"};bc={};_.ec=function(a,b){var c=_.Kb();a=c?c.createHTML(a):a;return new _.cc(a,b,bc)};_.fc=new _.cc(_.C.trustedTypes&&_.C.trustedTypes.emptyHTML||"",0,bc);_.gc=_.ec("<br>",0);
_.hc=_.Gb(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.dc(_.fc);return!b.parentElement});
_.ic=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.jc=2147483648*Math.random()|0;
_.kc=function(){return _.yb("iPhone")&&!_.yb("iPod")&&!_.yb("iPad")};_.lc=function(){return _.kc()||_.yb("iPad")||_.yb("iPod")};
var nc=function(a){nc[" "](a);return a};nc[" "]=_.Za;_.oc=function(a,b){try{return nc(a[b]),!0}catch(c){}return!1};_.pc=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};
var Fc,Gc,Mc,Qc;_.qc=_.Cb();_.rc=_.Db();_.sc=_.yb("Edge");_.tc=_.sc||_.rc;_.uc=_.yb("Gecko")&&!(-1!=_.ub.toLowerCase().indexOf("webkit")&&!_.yb("Edge"))&&!(_.yb("Trident")||_.yb("MSIE"))&&!_.yb("Edge");_.vc=-1!=_.ub.toLowerCase().indexOf("webkit")&&!_.yb("Edge");_.wc=_.vc&&_.yb("Mobile");_.xc=_.yb("Macintosh");_.yc=_.yb("Windows");_.zc=_.yb("Linux")||_.yb("CrOS");_.Ac=_.yb("Android");_.Bc=_.kc();_.Cc=_.yb("iPad");_.Dc=_.yb("iPod");_.Ec=_.lc();
Fc=function(){var a=_.C.document;return a?a.documentMode:void 0};a:{var Ic="",Jc=function(){var a=_.ub;if(_.uc)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.sc)return/Edge\/([\d\.]+)/.exec(a);if(_.rc)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.vc)return/WebKit\/(\S+)/.exec(a);if(_.qc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Jc&&(Ic=Jc?Jc[1]:"");if(_.rc){var Kc=Fc();if(null!=Kc&&Kc>parseFloat(Ic)){Gc=String(Kc);break a}}Gc=Ic}_.Lc=Gc;Mc={};
_.Nc=function(a){return _.pc(Mc,a,function(){return 0<=_.sb(_.Lc,a)})};_.Pc=function(a){return Number(_.Oc)>=a};if(_.C.document&&_.rc){var Rc=Fc();Qc=Rc?Rc:parseInt(_.Lc,10)||void 0}else Qc=void 0;_.Oc=Qc;

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Wc,Xc,Yc,ad,cd,ed,fd,gd,hd,id,jd,md,od,vd,wd,xd,yd,Gd,Hd;_.Sc=function(a,b){return _.ha[a]=b};_.Tc=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Tc);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.uK=!0};_.Uc=function(a){return Array.prototype.concat.apply([],arguments)};_.Vc=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Sb.prototype.uh=_.Sc(6,function(){return 1});_.cc.prototype.uh=_.Sc(5,function(){return this.yQ});
_.Nb.prototype.nd=_.Sc(4,function(){return this.YL});_.Sb.prototype.nd=_.Sc(3,function(){return this.fK.toString()});_.Vb.prototype.nd=_.Sc(2,function(){return this.eK});_.Zb.prototype.nd=_.Sc(1,function(){return this.dK});_.cc.prototype.nd=_.Sc(0,function(){return this.cK.toString()});Wc=null;Xc=/^[\w+/_-]+[=]{0,2}$/;Yc=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&Xc.test(a)?a:""};
_.$c=function(a){if(a&&a!=_.C)return Yc(a.document);null===Wc&&(Wc=Yc(_.C.document));return Wc};ad=0;_.bd=function(a){return Object.prototype.hasOwnProperty.call(a,_.Va)&&a[_.Va]||(a[_.Va]=++ad)};_.O(_.Tc,Error);_.Tc.prototype.name="CustomError";_.dd=function(a,b){return 0==a.lastIndexOf(b,0)};ed=/&/g;fd=/</g;gd=/>/g;hd=/"/g;id=/'/g;jd=/\x00/g;md=/[\x00&<>"']/;
_.nd=function(a,b){if(b)a=a.replace(ed,"&amp;").replace(fd,"&lt;").replace(gd,"&gt;").replace(hd,"&quot;").replace(id,"&#39;").replace(jd,"&#0;");else{if(!md.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ed,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(fd,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gd,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(hd,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(id,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jd,"&#0;"))}return a};od={};
_.pd=function(a,b){this.gK=b===od?a:""};_.pd.prototype.Ch=!0;_.pd.prototype.nd=function(){return this.gK.toString()};_.pd.prototype.fA=!0;_.pd.prototype.uh=function(){return 1};_.qd=function(a){if(a instanceof _.pd&&a.constructor===_.pd)return a.gK;_.$a(a);return"type_error:TrustedResourceUrl"};_.rd=function(a){return _.qd(a).toString()};_.sd=function(a){var b=_.Kb();a=b?b.createScriptURL(a):a;return new _.pd(a,od)};_.td=function(a){return _.sd(_.Ob(a))};
_.ud=function(a){if(a instanceof _.Sb&&a.constructor===_.Sb)return a.fK;_.$a(a);return"type_error:SafeUrl"};vd=/^(?:audio\/(?:3gpp2|3gpp|aac|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|x-matroska|x-wav|wav|webm)|font\/\w+|image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon)|video\/(?:mpeg|mp4|ogg|webm|quicktime|x-matroska))(?:;\w+=(?:\w+|"[\w;,= ]+"))*$/i;wd=/^data:(.*);base64,[a-z0-9+\/]+=*$/i;
xd=function(a){a=String(a);a=a.replace(/(%0A|%0D)/g,"");var b=a.match(wd);return b&&vd.test(b[1])?new _.Sb(a,_.Qb):null};yd=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;_.zd=function(a){if(a instanceof _.Sb)return a;a="object"==typeof a&&a.Ch?a.nd():String(a);return yd.test(a)?new _.Sb(a,_.Qb):xd(a)};
_.Ad=function(a,b){if(a instanceof _.Sb)return a;a="object"==typeof a&&a.Ch?a.nd():String(a);if(b&&/^data:/i.test(a)&&(b=xd(a)||_.Tb,b.nd()==a))return b;yd.test(a)||(a="about:invalid#zClosurez");return new _.Sb(a,_.Qb)};_.Bd=function(a){if(a instanceof _.cc)return a;var b="object"==typeof a,c=null;b&&a.fA&&(c=a.uh());return _.ec(_.nd(b&&a.Ch?a.nd():String(a)),c)};_.Cd=function(a,b){if((0,_.hc)())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=_.dc(b)};
_.Dd=function(a,b){b=b instanceof _.Sb?b:_.Ad(b);a.href=_.ud(b)};_.Ed=function(a,b,c,d){a=a instanceof _.Sb?a:_.Ad(a);b=b||_.C;c=c instanceof _.Nb?_.Ob(c):c||"";return void 0!==d?b.open(_.ud(a),c,d,void 0):b.open(_.ud(a),c)};_.Fd=function(a){return a=_.nd(a,void 0)};Gd=!_.rc||_.Pc(9);Hd=!_.uc&&!_.rc||_.rc&&_.Pc(9)||_.uc&&_.Nc("1.9.1");_.Id=_.rc&&!_.Nc("9");_.Jd=_.rc||_.qc||_.vc;_.Kd=_.rc&&!_.Pc(9);
var Qd,Ud;_.Nd=function(a){return a?new _.Ld(_.Md(a)):cd||(cd=new _.Ld)};_.Od=function(a,b){return"string"===typeof b?a.getElementById(b):b};
_.Pd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&_.Xa(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a};
_.Rd=function(a,b){_.zb(b,function(c,d){c&&"object"==typeof c&&c.Ch&&(c=c.nd());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Qd.hasOwnProperty(d)?a.setAttribute(Qd[d],c):_.dd(d,"aria-")||_.dd(d,"data-")?a.setAttribute(d,c):a[d]=c})};Qd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Sd=function(a){return a?a.parentWindow||a.defaultView:window};_.Vd=function(a,b){var c=String(b[0]),d=b[1];if(!Gd&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',_.Fd(d.name),'"');if(d.type){c.push(' type="',_.Fd(d.type),'"');var e={};_.Bb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=_.Td(a,c);d&&("string"===typeof d?c.className=d:Array.isArray(d)?c.className=d.join(" "):_.Rd(c,d));2<b.length&&Ud(a,c,b,2);return c};
Ud=function(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!_.eb(f)||_.Ya(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(_.Ya(f)){var g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){g="function"==typeof f.item;break a}}g=!1}_.lb(g?_.Vc(f):f,e)}}};_.Wd=function(a){return _.Td(document,a)};
_.Td=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.Xd=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.Zd=function(a,b){Ud(_.Md(a),a,arguments,1)};_.$d=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.ae=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.be=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.ce=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return _.be(a)}};
_.de=function(a){return Hd&&void 0!=a.children?a.children:_.mb(a.childNodes,function(b){return 1==b.nodeType})};_.ee=function(a){return _.Ya(a)&&1==a.nodeType};_.fe=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Md=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.ge=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.$d(a),a.appendChild(_.Md(a).createTextNode(String(b)))};_.Ld=function(a){this.nb=a||_.C.document||document};_.h=_.Ld.prototype;_.h.Fa=_.Nd;_.h.tC=_.ka(7);_.h.tb=function(){return this.nb};_.h.H=function(a){return _.Od(this.nb,a)};
_.h.getElementsByTagName=function(a,b){return(b||this.nb).getElementsByTagName(String(a))};_.h.ta=function(a,b,c){return _.Vd(this.nb,arguments)};_.h.createElement=function(a){return _.Td(this.nb,a)};_.h.createTextNode=function(a){return this.nb.createTextNode(String(a))};_.h.wb=function(){var a=this.nb;return a.parentWindow||a.defaultView};_.h.appendChild=function(a,b){a.appendChild(b)};_.h.append=_.Zd;_.h.canHaveChildren=_.Xd;_.h.Hd=_.$d;_.h.qI=_.ae;_.h.removeNode=_.be;_.h.kR=_.ce;_.h.Qy=_.de;
_.h.isElement=_.ee;_.h.contains=_.fe;_.h.Fh=_.ka(8);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.he=window;_.ie=document;_.je=_.he.location;_.ke=/\[native code\]/;_.le=function(a,b,c){return a[b]=a[b]||c};_.me=function(){var a;if((a=Object.create)&&_.ke.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.ne=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.oe=function(a,b){a=a||{};for(var c in a)_.ne(a,c)&&(b[c]=a[c])};_.pe=_.le(_.he,"gapi",{});
_.re=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=decodeURIComponent(a[2])}catch(e){}return c};_.te=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);_.ue=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");
_.ve=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.xe=function(a,b,c){_.we(a,b,c,"add","at")};_.we=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};
_.ye=_.le(_.he,"___jsl",_.me());_.le(_.ye,"I",0);_.le(_.ye,"hel",10);
var ze,Ae,Be,Ce,De,Ee,Fe;ze=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};Ae=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};Be=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
Ce=function(a,b,c){if(b&&"object"===typeof b)for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&"___goc"===d&&"undefined"===typeof b[d]||(a[d]&&b[d]&&"object"===typeof a[d]&&"object"===typeof b[d]&&!Be(a[d])&&!Be(b[d])?Ce(a[d],b[d]):b[d]&&"object"===typeof b[d]?(a[d]=Be(b[d])?[]:{},Ce(a[d],b[d])):a[d]=b[d])};
De=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);try{var b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
Ee=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(c=a.pop());Ce(c,b);a.push(c)};
Fe=function(a){Ae(!0);var b=window.___gcfg,c=ze("cu"),d=window.___gu;b&&b!==d&&(Ee(c,b),window.___gu=b);b=ze("cu");var e=document.scripts||document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,ze("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),(f=d[e])?(g=
f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||""):f=void 0,(f=De(f))&&b.push(f));a&&Ee(c,a);d=ze("cd");a=0;for(b=d.length;a<b;++a)Ce(Ae(),d[a],!0);d=ze("ci");a=0;for(b=d.length;a<b;++a)Ce(Ae(),d[a],!0);a=0;for(b=c.length;a<b;++a)Ce(Ae(),c[a],!0)};_.R=function(a,b){var c=Ae();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b};
_.Ge=function(a,b){var c;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var g={};d=d[a[e]]=g}d[a[e]]=b}else c=a;Fe(c)};
var He=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.le(_.ye,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};
He&&He();Fe();
_.K("gapi.config.get",_.R);_.K("gapi.config.update",_.Ge);

_.Ie=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.eb(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};_.Je=function(a){for(var b={},c=0,d=0;d<a.length;){var e=a[d++];var f=e;f=_.Ya(f)?"o"+_.bd(f):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(b,f)||(b[f]=!0,a[c++]=e)}a.length=c};_.Ke=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};_.Le=function(a){return/^[\s\xa0]*$/.test(a)};
_.Me=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Pd(c,"*",a,b)[0]||null}return a||null};

var Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,zf,Af;Ue=void 0;Ve=function(a){try{return _.C.JSON.parse.call(_.C.JSON,a)}catch(b){return!1}};We=function(a){return Object.prototype.toString.call(a)};Xe=We(0);Ye=We(new Date(0));Ze=We(!0);$e=We("");af=We({});bf=We([]);
cf=function(a,b){if(b)for(var c=0,d=b.length;c<d;++c)if(a===b[c])throw new TypeError("Converting circular structure to JSON");d=typeof a;if("undefined"!==d){c=Array.prototype.slice.call(b||[],0);c[c.length]=a;b=[];var e=We(a);if(null!=a&&"function"===typeof a.toJSON&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(e!==bf||a.constructor!==Array&&a.constructor!==Object)&&(e!==af||a.constructor!==Array&&a.constructor!==Object)&&e!==$e&&e!==Xe&&e!==Ze&&e!==Ye))return cf(a.toJSON.call(a),c);if(null==
a)b[b.length]="null";else if(e===Xe)a=Number(a),isNaN(a)||isNaN(a-a)?a="null":-0===a&&0>1/a&&(a="-0"),b[b.length]=String(a);else if(e===Ze)b[b.length]=String(!!Number(a));else{if(e===Ye)return cf(a.toISOString.call(a),c);if(e===bf&&We(a.length)===Xe){b[b.length]="[";var f=0;for(d=Number(a.length)>>0;f<d;++f)f&&(b[b.length]=","),b[b.length]=cf(a[f],c)||"null";b[b.length]="]"}else if(e==$e&&We(a.length)===Xe){b[b.length]='"';f=0;for(c=Number(a.length)>>0;f<c;++f)d=String.prototype.charAt.call(a,f),
e=String.prototype.charCodeAt.call(a,f),b[b.length]="\b"===d?"\\b":"\f"===d?"\\f":"\n"===d?"\\n":"\r"===d?"\\r":"\t"===d?"\\t":"\\"===d||'"'===d?"\\"+d:31>=e?"\\u"+(e+65536).toString(16).substr(1):32<=e&&65535>=e?d:"\ufffd";b[b.length]='"'}else if("object"===d){b[b.length]="{";d=0;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(e=cf(a[f],c),void 0!==e&&(d++&&(b[b.length]=","),b[b.length]=cf(f),b[b.length]=":",b[b.length]=e));b[b.length]="}"}else return}return b.join("")}};df=/[\0-\x07\x0b\x0e-\x1f]/;
ef=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;ff=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;gf=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;hf=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;jf=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;kf=/[ \t\n\r]+/g;lf=/[^"]:/;mf=/""/g;nf=/true|false|null/g;of=/00/;pf=/[\{]([^0\}]|0[^:])/;qf=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;rf=/[^\[,:][\[\{]/;sf=/^(\{|\}|\[|\]|,|:|0)+/;tf=/\u2028/g;
uf=/\u2029/g;
vf=function(a){a=String(a);if(df.test(a)||ef.test(a)||ff.test(a)||gf.test(a))return!1;var b=a.replace(hf,'""');b=b.replace(jf,"0");b=b.replace(kf,"");if(lf.test(b))return!1;b=b.replace(mf,"0");b=b.replace(nf,"0");if(of.test(b)||pf.test(b)||qf.test(b)||rf.test(b)||!b||(b=b.replace(sf,"")))return!1;a=a.replace(tf,"\\u2028").replace(uf,"\\u2029");b=void 0;try{b=Ue?[Ve(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(c){return!1}return b&&1===
b.length?b[0]:!1};wf=function(){var a=((_.C.document||{}).scripts||[]).length;if((void 0===Se||void 0===Ue||Te!==a)&&-1!==Te){Se=Ue=!1;Te=-1;try{try{Ue=!!_.C.JSON&&'{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'===_.C.JSON.stringify.call(_.C.JSON,{a:[3,!0,new Date(0)],c:function(){}})&&!0===Ve("true")&&3===Ve('[{"a":3}]')[0].a}catch(b){}Se=Ue&&!Ve("[00]")&&!Ve('"\u0007"')&&!Ve('"\\0"')&&!Ve('"\\v"')}finally{Te=a}}};_.xf=function(a){if(-1===Te)return!1;wf();return(Se?Ve:vf)(a)};
_.yf=function(a){if(-1!==Te)return wf(),Ue?_.C.JSON.stringify.call(_.C.JSON,a):cf(a)};zf=!Date.prototype.toISOString||"function"!==typeof Date.prototype.toISOString||"1970-01-01T00:00:00.000Z"!==(new Date(0)).toISOString();
Af=function(){var a=Date.prototype.getUTCFullYear.call(this);return[0>a?"-"+String(1E6-a).substr(1):9999>=a?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1),
"Z"].join("")};Date.prototype.toISOString=zf?Af:Date.prototype.toISOString;

var Bf;Bf=window.console;_.Cf=function(a){Bf&&Bf.log&&Bf.log(a)};_.Df=function(a){Bf&&(Bf.error?Bf.error(a):Bf.log&&Bf.log(a))};_.Ef=function(a){Bf&&(Bf.warn?Bf.warn(a):Bf.log&&Bf.log(a))};_.Ff=function(){};

_.qg=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));c=a.substring(0,a.indexOf("://"));if(!c)throw Error("s`"+a);if("http"!==c&&"https"!==c&&"chrome-extension"!==c&&"moz-extension"!==c&&"file"!==c&&"android-app"!==c&&"chrome-search"!==c&&"chrome-untrusted"!==c&&"chrome"!==c&&"app"!==c&&"devtools"!==
c)throw Error("t`"+c);a="";var d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1);b=b.substring(0,d);if("http"===c&&"80"!==e||"https"===c&&"443"!==e)a=":"+e}return c+"://"+b+a};

_.xh=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};_.yh=function(a){var b=_.xh();if(!a)return b;a=a.split("/");for(var c=0,d=a.length;b&&"object"===typeof b&&c<d;++c)b=b[a[c]];return c===a.length&&void 0!==b?b:void 0};

var hl=function(){this.Qr={qK:al?"../"+al:null,hy:bl,nH:cl,u9:dl,Wt:el,h$:fl};this.$e=_.he;this.YJ=this.zQ;this.oR=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.Qr.qK){this.$e=this.Qr.nH(this.$e,this.Qr.qK);var a=this.$e.document,b=a.createElement("script");b.setAttribute("type","text/javascript");b.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(b);this.YJ=this.$e.doPostMsg}this.LC={};this.kD={};a=(0,_.P)(this.Jz,
this);_.xe(this.$e,"message",a);_.le(_.ye,"RPMQ",[]).push(a);this.$e!=this.$e.parent&&gl(this,this.$e.parent,this.MA(this.$e.name),"*")};hl.prototype.MA=function(a){return'{"h":"'+escape(a)+'"}'};var il=function(a){var b=null;0===a.indexOf('{"h":"')&&a.indexOf('"}')===a.length-2&&(b=unescape(a.substring(6,a.length-2)));return b},ml=function(a){if(!/^\s*{/.test(a))return!1;a=_.xf(a);return null!==a&&"object"===typeof a&&!!a.g};
hl.prototype.Jz=function(a){var b=String(a.data);(0,_.Ff)("gapi.rpc.receive("+dl+"): "+(!b||512>=b.length?b:b.substr(0,512)+"... ("+b.length+" bytes)"));var c=0!==b.indexOf("!_");c||(b=b.substring(2));var d=ml(b);if(!c&&!d){if(!d&&(c=il(b))){if(this.LC[c])this.LC[c]();else this.kD[c]=1;return}var e=a.origin,f=this.Qr.hy;this.oR?_.he.setTimeout(function(){f(b,e)},0):f(b,e)}};hl.prototype.Ec=function(a,b){".."===a||this.kD[a]?(b(),delete this.kD[a]):this.LC[a]=b};
var gl=function(a,b,c,d){var e=ml(c)?"":"!_";(0,_.Ff)("gapi.rpc.send("+dl+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));a.YJ(b,e+c,d)};hl.prototype.zQ=function(a,b,c){a.postMessage(b,c)};hl.prototype.send=function(a,b,c){(a=this.Qr.nH(this.$e,a))&&!a.closed&&gl(this,a,b,c)};
var nl,ol,pl,ql,rl,sl,tl,al,dl,ul,vl,wl,cl,el,yl,zl,El,Fl,Hl,fl,Jl,Il,Al,Bl,Kl,bl,Ll,Ml;nl=0;ol=[];pl={};ql={};rl=_.he.location.href;sl=_.re(rl,"rpctoken");tl=_.re(rl,"parent")||_.ie.referrer;al=_.re(rl,"rly");dl=al||(_.he!==_.he.top||_.he.opener)&&_.he.name||"..";ul=null;vl={};wl=function(){};_.xl={send:wl,Ec:wl,MA:wl};
cl=function(a,b){"/"==b.charAt(0)&&(b=b.substring(1),a=_.he.top);if(0===b.length)return a;for(b=b.split("/");b.length;){var c=b.shift();"{"==c.charAt(0)&&"}"==c.charAt(c.length-1)&&(c=c.substring(1,c.length-1));if(".."===c)a=a==a.parent?a.opener:a.parent;else if(".."!==c&&a.frames[c]){if(a=a.frames[c],!("postMessage"in a))throw"Not a window";}else return null}return a};el=function(a){return(a=pl[a])&&a.Ck};
yl=function(a){if(a.f in{})return!1;var b=a.t,c=pl[a.r];a=a.origin;return c&&(c.Ck===b||!c.Ck&&!b)&&(a===c.origin||"*"===c.origin)};zl=function(a){var b=a.id.split("/"),c=b[b.length-1],d=a.origin;return function(e){var f=e.origin;return e.f==c&&(d==f||"*"==d)}};_.Cl=function(a,b,c){a=Al(a);ql[a.name]={Hg:b,wq:a.wq,qo:c||yl};Bl()};_.Dl=function(a){delete ql[Al(a).name]};El={};Fl=function(a,b){(a=El["_"+a])&&a[1](this)&&a[0].call(this,b)};
Hl=function(a){var b=a.c;if(!b)return wl;var c=a.r,d=a.g?"legacy__":"";return function(){var e=[].slice.call(arguments,0);e.unshift(c,d+"__cb",null,b);_.Gl.apply(null,e)}};fl=function(a){ul=a};Jl=function(a){vl[a]||(vl[a]=_.he.setTimeout(function(){vl[a]=!1;Il(a)},0))};Il=function(a){var b=pl[a];if(b&&b.ready){var c=b.DB;for(b.DB=[];c.length;)_.xl.send(a,_.yf(c.shift()),b.origin)}};Al=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),wq:!0}:{name:a,wq:!1}};
Bl=function(){for(var a=_.yh("rpc/residenceSec")||60,b=(new Date).getTime()/1E3,c=0,d;d=ol[c];++c){var e=d.rpc;if(!e||0<a&&b-d.timestamp>a)ol.splice(c,1),--c;else{var f=e.s,g=ql[f]||ql["*"];if(g)if(ol.splice(c,1),--c,e.origin=d.origin,d=Hl(e),e.callback=d,g.qo(e)){if("__cb"!==f&&!!g.wq!=!!e.g)break;e=g.Hg.apply(e,e.a);void 0!==e&&d(e)}else(0,_.Ff)("gapi.rpc.rejected("+dl+"): "+f)}}};Kl=function(a,b,c){ol.push({rpc:a,origin:b,timestamp:(new Date).getTime()/1E3});c||Bl()};
bl=function(a,b){a=_.xf(a);Kl(a,b,!1)};Ll=function(a){for(;a.length;)Kl(a.shift(),this.origin,!0);Bl()};Ml=function(a){var b=!1;a=a.split("|");var c=a[0];0<=c.indexOf("/")&&(b=!0);return{id:c,origin:a[1]||"*",sA:b}};
_.Nl=function(a,b,c,d){var e=Ml(a);d&&(_.he.frames[e.id]=_.he.frames[e.id]||d);a=e.id;if(!pl.hasOwnProperty(a)){c=c||null;d=e.origin;if(".."===a)d=_.qg(tl),c=c||sl;else if(!e.sA){var f=_.ie.getElementById(a);f&&(f=f.src,d=_.qg(f),c=c||_.re(f,"rpctoken"))}"*"===e.origin&&d||(d=e.origin);pl[a]={Ck:c,DB:[],origin:d,dY:b,lK:function(){var g=a;pl[g].ready=1;Il(g)}};_.xl.Ec(a,pl[a].lK)}return pl[a].lK};
_.Gl=function(a,b,c,d){a=a||"..";_.Nl(a);a=a.split("|",1)[0];var e=b,f=[].slice.call(arguments,3),g=c,k=dl,l=sl,m=pl[a],n=k,r=Ml(a);if(m&&".."!==a){if(r.sA){if(!(l=pl[a].dY)){l=ul?ul.substring(1).split("/"):[dl];n=l.length-1;for(var u=_.he.parent;u!==_.he.top;){var q=u.parent;if(!n--){for(var v=null,t=q.frames.length,w=0;w<t;++w)q.frames[w]==u&&(v=w);l.unshift("{"+v+"}")}u=q}l="/"+l.join("/")}n=l}else n=k="..";l=m.Ck}g&&r?(m=yl,r.sA&&(m=zl(r)),El["_"+ ++nl]=[g,m],g=nl):g=null;f={s:e,f:k,r:n,t:l,c:g,
a:f};e=Al(e);f.s=e.name;f.g=e.wq;pl[a].DB.push(f);Jl(a)};if("function"===typeof _.he.postMessage||"object"===typeof _.he.postMessage)_.xl=new hl,_.Cl("__cb",Fl,function(){return!0}),_.Cl("_processBatch",Ll,function(){return!0}),_.Nl("..");

_.K("gapi.rpc.setup",_.Nl);_.K("gapi.rpc.register",_.Cl);_.K("gapi.rpc.call",_.Gl);_.K("gapi.rpc.unregister",_.Dl);_.K("gapi.rpc.sendHandshake",function(a,b){_.Nl(a)();_.xl.send(a,_.xl.MA(b),"*")});

});
// Google Inc.
